@startuml Sequence

    participant Main
    participant Configuration
    ' participant Maze
    participant Benchmark
    participant Verifier
    participant MazeAlgorithm

    Main ++
    Main -> Configuration ++: load(args: String[])
    Main <-- Configuration --: return config

    alt Benchmark Mode
    |||
    Main -> Benchmark ++: runBenchmark()
    Main <-- Benchmark
    |||
    Main -> Benchmark: generateReport()
    Main <-- Benchmark --: return report
    |||
    else Verification Mode
    |||
    Main -> Verifier ++: verify()
    Main <-- Verifier --: return result
    |||
    else Solve Mode
    |||
    Main -> MazeAlgorithm ++: getPath(maze: Maze, factorized: boolean)
    Main <-- MazeAlgorithm --: return path
    |||
    end

@enduml